name: flutter_application_1
description: "SmartSpend: Pengelola Anggaran & Target Tabungan"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0 # Sesuaikan dengan versi SDK yang kamu gunakan

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Komunikasi Data (REST API)
  http: ^1.2.1
  
  # Firebase Core & Auth
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.6.12
  
  # Formating (Mata Uang & Tanggal)
  intl: ^0.19.0
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true